// https://github.com/adzen/chu2view/blob/main/chu2.htm

export function internal_level_list(){
	return [
	  {title: "▲MEW▲△MEW△CAKE", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.3},
	  {title: "前前前世", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.9},
	  {title: "God knows...", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.3},
	  {title: "五等分の気持ち", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.4},
	  {title: "ただ君に晴れ", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 10.8},
	  {title: "ゴーゴー幽霊船", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.5},
	  {title: "ようこそジャパリパークへ", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.1},
	  {title: "ラブリー☆えんじぇる!!", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.3},
	  {title: "シュガーソングとビターステップ", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.2},
	  {title: "ワールズエンド・ダンスホール", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.3},
	  {title: "ヒビカセ", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.5},
	  {title: "白い雪のプリンセスは", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.2},
	  {title: "イカサマライフゲイム", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.2},
	  {title: "一触即発☆禅ガール", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.3},
	  {title: "命に嫌われている", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.7},
	  {title: "乙女解剖", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.8},
	  {title: "フィクサー", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.5},
	  {title: "ダブルラリアット", BASIC: 0, ADVANCED: 0, EXPERT: 9.2, MASTER: 11.3},
	  {title: "アマツキツネ", BASIC: 0, ADVANCED: 0, EXPERT: 9.1, MASTER: 11.8},
	  {title: "桜ノ雨", BASIC: 0, ADVANCED: 0, EXPERT: 8.0, MASTER: 11.0},
	  {title: "リモコン", BASIC: 0, ADVANCED: 0, EXPERT: 8.6, MASTER: 11.8},
	  {title: "カミサマネジマキ", BASIC: 0, ADVANCED: 0, EXPERT: 11.0, MASTER: 13.0},
	  {title: "初音ミクの消失", BASIC: 0, ADVANCED: 0, EXPERT: 11.9, MASTER: 13.4},
	  {title: "みくみくにしてあげる♪【してやんよ】", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.5},
	  {title: "愛言葉", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.5},
	  {title: "ビバハピ", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.9},
	  {title: "Hand in Hand", BASIC: 0, ADVANCED: 5.0, EXPERT: 0, MASTER: 11.7},
	  {title: "ODDS&ENDS", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 10.6},
	  {title: "ユクエシレズ", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 10.8},
	  {title: "ぼくらの16bit戦争", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 13.0},
	  {title: "すろぉもぉしょん", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.3},
	  {title: "裏表ラバーズ", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.8},
	  {title: "ネトゲ廃人シュプレヒコール", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.9},
	  {title: "おねがいダーリン", BASIC: 0, ADVANCED: 6.0, EXPERT: 0, MASTER: 12.1},
	  {title: "カゲロウデイズ", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.7},
	  {title: "ロキ", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.0},
	  {title: "放課後ストライド", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.1},
	  {title: "アンノウン・マザーグース", BASIC: 0, ADVANCED: 0, EXPERT: 9.3, MASTER: 12.6},
	  {title: "いーあるふぁんくらぶ", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.4},
	  {title: "ウミユリ海底譚", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.1},
	  {title: "アスノヨゾラ哨戒班", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.4},
	  {title: "天樂", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.2},
	  {title: "Crazy ∞ nighT", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.5},
	  {title: "脳漿炸裂ガール", BASIC: 0, ADVANCED: 7.0, EXPERT: 0, MASTER: 12.7},
	  {title: "FREELY TOMORROW", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.4},
	  {title: "ギガンティックO.T.N", BASIC: 0, ADVANCED: 6.0, EXPERT: 10.0, MASTER: 13.0},
	  {title: "シリョクケンサ", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.5},
	  {title: "セツナトリップ", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.7},
	  {title: "六兆年と一夜物語", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.5},
	  {title: "Sweet Devil", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.9},
	  {title: "天ノ弱", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.1},
	  {title: "ストリーミングハート", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.4},
	  {title: "腐れ外道とチョコレゐト", BASIC: 0, ADVANCED: 0, EXPERT: 9.7, MASTER: 12.3},
	  {title: "M.S.S.Planet", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.9},
	  {title: "タイガーランペイジ", BASIC: 0, ADVANCED: 0, EXPERT: 9.9, MASTER: 12.5},
	  {title: "ロストワンの号哭", BASIC: 0, ADVANCED: 6.0, EXPERT: 0, MASTER: 12.4},
	  {title: "Calamity Fortune", BASIC: 0, ADVANCED: 8.7, EXPERT: 11.5, MASTER: 13.7},
	  {title: "儚きもの人間", BASIC: 0, ADVANCED: 0, EXPERT: 9.9, MASTER: 12.5},
	  {title: "最終鬼畜妹フランドール・S", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 13.4},
	  {title: "華鳥風月", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.5},
	  {title: "最終鬼畜妹・一部声", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 13.0},
	  {title: "緋色のDance", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.2},
	  {title: "四次元跳躍機関", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.7},
	  {title: "Yet Another ”drizzly rain”", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.7},
	  {title: "エピクロスの虹はもう見えない", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 10.0},
	  {title: "Grip & Break down !!", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.3},
	  {title: "Scream out! -CHUNITHM Tuning-", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.4},
	  {title: "WARNING×WARNING×WARNING", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.4},
	  {title: "taboo tears you up", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.8},
	  {title: "Imperishable Night 2006 (2016 Refine)", BASIC: 0, ADVANCED: 0, EXPERT: 11.5, MASTER: 13.6},
	  {title: "月に叢雲華に風", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.1},
	  {title: "幻想のサテライト", BASIC: 0, ADVANCED: 0, EXPERT: 11.0, MASTER: 13.1},
	  {title: "Bad Apple!! feat.nomico", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.0},
	  {title: "ナイト・オブ・ナイツ", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.9},
	  {title: "sweet little sister", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.6},
	  {title: "Dreaming", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.7},
	  {title: "Unlimited Spark!", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.8},
	  {title: "FLOWER", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.3},
	  {title: "ちくわパフェだよ☆CKP", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.2},
	  {title: "Elemental Creation", BASIC: 0, ADVANCED: 0, EXPERT: 11.3, MASTER: 13.5},
	  {title: "アルストロメリア", BASIC: 0, ADVANCED: 0, EXPERT: 9.7, MASTER: 12.2},
	  {title: "凛として咲く花の如く", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.2},
	  {title: "Evans", BASIC: 0, ADVANCED: 0, EXPERT: 10.8, MASTER: 13.4},
	  {title: "Finite", BASIC: 0, ADVANCED: 0, EXPERT: 10.9, MASTER: 13.9},
	  {title: "神威", BASIC: 0, ADVANCED: 0, EXPERT: 12.7, MASTER: 13.9},
	  {title: "Brain Power", BASIC: 0, ADVANCED: 0, EXPERT: 11.0, MASTER: 13.3},
	  {title: "BlythE", BASIC: 0, ADVANCED: 0, EXPERT: 11.6, MASTER: 13.2},
	  {title: "Super Lovely (Heavenly Remix)", BASIC: 0, ADVANCED: 0, EXPERT: 9.5, MASTER: 13.4},
	  {title: "Ladymade Star", BASIC: 0, ADVANCED: 0, EXPERT: 8.4, MASTER: 11.7},
	  {title: "Memory of Beach", BASIC: 0, ADVANCED: 0, EXPERT: 10.3, MASTER: 12.7},
	  {title: "SON OF SUN", BASIC: 0, ADVANCED: 0, EXPERT: 12.7, MASTER: 13.8},
	  {title: "Sound Chimera", BASIC: 0, ADVANCED: 9.0, EXPERT: 11.0, MASTER: 13.8},
	  {title: "セイクリッド　ルイン", BASIC: 0, ADVANCED: 0, EXPERT: 11.3, MASTER: 13.5},
	  {title: "極圏", BASIC: 0, ADVANCED: 0, EXPERT: 11.7, MASTER: 13.6},
	  {title: "Scarlet Lance", BASIC: 0, ADVANCED: 0, EXPERT: 11.9, MASTER: 13.6},
	  {title: "Taiko Drum Monster", BASIC: 0, ADVANCED: 0, EXPERT: 11.5, MASTER: 13.4},
	  {title: "GERBERA", BASIC: 0, ADVANCED: 0, EXPERT: 11.7, MASTER: 13.6},
	  {title: "ouroboros -twin stroke of the end-", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 13.7},
	  {title: "L9", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.6},
	  {title: "Altale", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.7},
	  {title: "Aragami", BASIC: 0, ADVANCED: 0, EXPERT: 9.3, MASTER: 13.5},
	  {title: "B.B.K.K.B.K.K.", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.8},
	  {title: "Halcyon", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 13.3},
	  {title: "DRAGONLADY", BASIC: 0, ADVANCED: 0, EXPERT: 11.4, MASTER: 13.2},
	  {title: "FREEDOM DiVE", BASIC: 0, ADVANCED: 8.5, EXPERT: 11.5, MASTER: 13.8},
	  {title: "DataErr0r", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 13.0},
	  {title: "GOODTEK", BASIC: 0, ADVANCED: 0, EXPERT: 10.7, MASTER: 13.3},
	  {title: "AVALON", BASIC: 0, ADVANCED: 0, EXPERT: 11.7, MASTER: 13.5},
	  {title: "Destr0yer", BASIC: 0, ADVANCED: 0, EXPERT: 11.2, MASTER: 13.5},
	  {title: "檄!帝国華撃団", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.3},
	  {title: "Through The Tower", BASIC: 0, ADVANCED: 0, EXPERT: 9.5, MASTER: 12.4},
	  {title: "ハート・ビート", BASIC: 0, ADVANCED: 0, EXPERT: 10.0, MASTER: 12.1},
	  {title: "brilliant better", BASIC: 0, ADVANCED: 0, EXPERT: 10.0, MASTER: 11.8},
	  {title: "フォルテシモBELL", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.0},
	  {title: "私の中の幻想的世界観及びその顕現を想起させたある現実での出来事に関する一考察", 
		BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.5},
	  {title: "DETARAME ROCK&ROLL THEORY", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.2},
	  {title: "猛進ソリストライフ！", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.2},
	  {title: "My Dearest Song", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.2},
	  {title: "Change Our MIRAI！", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.8},
	  {title: "無敵We are one!!", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.1},
	  {title: "ドキドキDREAM!!!", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.1},
	  {title: "Still", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.5},
	  {title: "言ノ葉カルマ", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.0},
	  {title: "言ノ葉遊戯", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.6},
	  {title: "洗脳", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.5},
	  {title: "空威張りビヘイビア", BASIC: 0, ADVANCED: 0, EXPERT: 9.0, MASTER: 12.3},
	  {title: "天国と地獄 -言ノ葉リンネ-", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.8},
	  {title: "悪戯", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.2},
	  {title: "りばーぶ", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.2},
	  {title: "Barbed Eye", BASIC: 0, ADVANCED: 0, EXPERT: 9.4, MASTER: 12.0},
	  {title: "分からない", BASIC: 0, ADVANCED: 0, EXPERT: 10.7, MASTER: 13.2},
	  {title: "相思創愛", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.4},
	  {title: "咲キ誇レ常世ノ華", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.4},
	  {title: "Garakuta Doll Play", BASIC: 0, ADVANCED: 0, EXPERT: 12.3, MASTER: 13.8},
	  {title: "Like the Wind [Reborn]", BASIC: 0, ADVANCED: 0, EXPERT: 11.0, MASTER: 13.5},
	  {title: "AMAZING MIGHTYYYY!!!!", BASIC: 0, ADVANCED: 0, EXPERT: 12.0, MASTER: 13.8},
	  {title: "VERTeX", BASIC: 0, ADVANCED: 0, EXPERT: 11.9, MASTER: 13.7},
	  {title: "Hyper Active", BASIC: 0, ADVANCED: 0, EXPERT: 10.7, MASTER: 13.3},
	  {title: "L'épilogue", BASIC: 0, ADVANCED: 0, EXPERT: 9.8, MASTER: 12.5},
	  {title: "D✪N’T ST✪P R✪CKIN’ ～[✪_✪] MIX～", BASIC: 0, ADVANCED: 0, EXPERT: 9.5, MASTER: 12.5},
	  {title: "Caliburne ～Story of the Legendary sword～", BASIC: 0, ADVANCED: 0, EXPERT: 12.2, MASTER: 13.8},
	  {title: "ねぇ、壊れタ人形ハ何処へ棄テらレるノ？", BASIC: 0, ADVANCED: 0, EXPERT: 12.4, MASTER: 13.8},
	  {title: "larva", BASIC: 0, ADVANCED: 0, EXPERT: 11.9, MASTER: 13.7},
	  {title: "CITRUS MONSTER", BASIC: 0, ADVANCED: 0, EXPERT: 12.0, MASTER: 13.6},
	  {title: "CYCLES", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.9},
	  {title: "高気圧ねこロック", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.6},
	  {title: "FEEL the BEATS", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.9},
	  {title: "夢花火", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.3},
	  {title: "Excalibur ～Revived resolution～", BASIC: 0, ADVANCED: 0, EXPERT: 12.3, MASTER: 13.8},
	  {title: "Alea jacta est!", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 13.7},
	  {title: "STARTLINER", BASIC: 0, ADVANCED: 0, EXPERT: 7.9, MASTER: 10.6},
	  {title: "Viyella's Tears", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 13.9},
	  {title: "Invitation", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.3},
	  {title: "ＧＯ！ＧＯ！ラブリズム♥", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.1},
	  {title: "Theme of SeelischTact", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.5},
	  {title: "Infantoon Fantasy", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.4},
	  {title: "Counselor", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.7},
	  {title: "Guilty", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.9},
	  {title: "幾四音-Ixion-", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.3},
	  {title: "Grab your sword", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 10.5},
	  {title: "My First Phone", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.8},
	  {title: "今ぞ♡崇め奉れ☆オマエらよ！！～姫の秘メタル渇望～", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.8},
	  {title: "Anemone", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.1},
	  {title: "リリーシア", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.0},
	  {title: "砂漠のハンティングガール♡", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.1},
	  {title: "昵懇レファレンス", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.2},
	  {title: "Teriqma", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.3},
	  {title: "After the rain", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.3},
	  {title: "The ether", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.2},
	  {title: "We Gonna Journey", BASIC: 0, ADVANCED: 0, EXPERT: 11.0, MASTER: 13.1},
	  {title: "overcome", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.0},
	  {title: "Memories of Sun and Moon", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.5},
	  {title: "luna blu", BASIC: 0, ADVANCED: 0, EXPERT: 12.4, MASTER: 13.5},
	  {title: "閃鋼のブリューナク", BASIC: 0, ADVANCED: 0, EXPERT: 11.9, MASTER: 13.5},
	  {title: "Gate of Fate", BASIC: 0, ADVANCED: 0, EXPERT: 11.7, MASTER: 13.4},
	  {title: "こころここから", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 10.3},
	  {title: "The wheel to the right", BASIC: 0, ADVANCED: 0, EXPERT: 11.9, MASTER: 13.4},
	  {title: "Alma", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.7},
	  {title: "STAR", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.4},
	  {title: "Tango Rouge", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 13.1},
	  {title: "Gustav Battle", BASIC: 0, ADVANCED: 0, EXPERT: 12.2, MASTER: 13.0},
	  {title: "怒槌", BASIC: 0, ADVANCED: 0, EXPERT: 12.8, MASTER: 14.0},
	  {title: "夕暮れワンルーム", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.7},
	  {title: "乗り切れ受験ウォーズ", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 11.5},
	  {title: "stella=steLLa", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.7},
	  {title: "とーきょー全域★アキハバラ？", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.5},
	  {title: "エンドマークに希望と涙を添えて", BASIC: 0, ADVANCED: 0, EXPERT: 11.7, MASTER: 13.8},
	  {title: "SNIPE WHOLE", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.7},
	  {title: "MUSIC PЯAYER", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.8},
	  {title: "Cyberozar", BASIC: 0, ADVANCED: 0, EXPERT: 11.1, MASTER: 13.2},
	  {title: "Genesis", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 13.5},
	  {title: "名も無い鳥", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.5},
	  {title: "L'épisode", BASIC: 0, ADVANCED: 0, EXPERT: 12.1, MASTER: 13.6},
	  {title: "GOLDEN RULE", BASIC: 0, ADVANCED: 0, EXPERT: 11.0, MASTER: 13.6},
	  {title: "宛城、炎上！！", BASIC: 0, ADVANCED: 0, EXPERT: 12.2, MASTER: 13.8},
	  {title: "Trrricksters!!", BASIC: 0, ADVANCED: 0, EXPERT: 12.7, MASTER: 14.0},
	  {title: "《混乱》 ～ Muspell", BASIC: 0, ADVANCED: 0, EXPERT: 11.0, MASTER: 12.7},
	  {title: "《理想》 ～ Cloudland", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.2},
	  {title: "《逃避》 ～ The Deserter", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.9},
	  {title: "《最愛》 ～ Curse", BASIC: 0, ADVANCED: 0, EXPERT: 0, MASTER: 12.6},
	  {title: "《運命》 ～ Ray of Hope", BASIC: 0, ADVANCED: 0, EXPERT: 11.4, MASTER: 13.4},
	  {title: "《破滅》 ～ Rhapsody for The End", BASIC: 0, ADVANCED: 0, EXPERT: 12.4, MASTER: 13.9},
	  {title: "玩具狂奏曲 -終焉-", BASIC: 0, ADVANCED: 0, EXPERT: 12.7, MASTER: 14.0},
	  {title: "TiamaT:F minor", BASIC: 0, ADVANCED: 0, EXPERT: 12.7, MASTER: 14.0},
	  {title: "混沌を越えし我らが神聖なる調律主を讃えよ", BASIC: 0, ADVANCED: 0, EXPERT: 13.3, MASTER: 14.1},
	  {title: "GIGA DRIVE", BASIC: 0, ADVANCED: 0, EXPERT: 12.7, MASTER: 13.9},
	  {title: "Contrapasso -inferno-", BASIC: 0, ADVANCED: 0, EXPERT: 12.1, MASTER: 13.9},
	];
}